### ISSUE TITLE
is it normal that i'm getting 1 mb/s down ? i've used filza(webdav server option) before and gotten 4 mb/s!

### ISSUE THREAD

**Issue by lidwan5** [Absolucy/xenon#24]

**Comment by lidwan5** [comment]
using xenon on ios 14.3 and the client is on popos linux

**Comment by QziP22** [comment]
Whenever I try to drag-n-drop any type of file, the progress bar stops about halfway and it never finishes. I too have that problem

**Comment by aspenluxxxy** [comment]
The client is currently being rewritten to be less of an unstable mess.
