### ISSUE TITLE
Ios 14.4.1 Xenon Crash

### ISSUE THREAD

**Issue by LiamW2000** [Absolucy/xenon#29]
https://user-images.githubusercontent.com/47453533/141607633-4fc6f610-bad8-4f5a-b9a6-8448014015b2.mov

## Describe the bug
Crashing when attempting to pair computer

## To Reproduce
1. Open Xenon settings 
2. Tap Pair with Computer
3. Watch app crash

## Expected behavior
Considering the instructions, i’d imagine it’s meant to open a qr reader of some sort

## Screenshots
Added screen recording

## Setup (please complete the following information):
 - iOS 14.4.1
 - Fugu14 + Unc0ver setup
 - Windows 10

## Additional context
I just bought this tweak and was hoping it would work

**Comment by Absolucy** [comment]
Test the 2.0 beta and see if that works:  https://discord.com/invite/8f4XNYjhuU

**Comment by LiamW2000** [comment]
Hi thanks for the quick reply. How do i install the beta version on my phone. Impactor?

**Comment by Absolucy** [comment]
no, just open the deb in cydia/sileo/filza/whatever.

**Comment by LiamW2000** [comment]
![Uploading AB31BA21-19DD-4EF4-986A-C92F3549D7AA.png…]()

**Comment by LiamW2000** [comment]
![891A74AE-2170-472B-AA47-4EC9F2B60CB1](https://user-images.githubusercontent.com/47453533/141607998-7dd41816-6d8c-4e7a-91ae-8c8b502058cb.png)

**Comment by LiamW2000** [comment]
https://user-images.githubusercontent.com/47453533/141608194-4e06e447-0978-426b-ae76-d365806015c9.MP4

**Comment by Absolucy** [comment]
@LiamW2000 cr4shed log?

**Comment by LiamW2000** [comment]
Cr4shed isn’t saying anything about it when it does die. It just force closes the tweak settings app

**Comment by LiamW2000** [comment]
This was in the panic log file
![AC856EB5-2BA9-4131-9CB1-912798C76770](https://user-images.githubusercontent.com/47453533/141608699-630337e8-6c4b-464f-b37a-6fa31b220e9b.png)
